#!/usr/bin/env bash

#
# inspo: https://github.com/0ut4L/dotfiles/blob/main/tmux/.tmux.conf
#
# TODO: before starting, git clone https://github.com/tmux-plugins/tpm ~/.dotfiles/tmux/.config/tmux/plugins/tpm
#
# To reload this: `stow tmux` first to ensure symlinks exist in `~/.config` and then `tmux source ~/.config/tmux/tmux.conf`
#
# Note: remember to <prefix>+I (capital I) to reload configuration
#
# See [w]indows: <prefix>+w (then navigate with jk, delete with "x")
# [c]reate new window: <prefix>+c
# [p]revious/[n]ext window: <prefix>+p/n

# Default prefix is C-a instead of C-b (more ergonomic in QWERTY)
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Enable mouse interactions (pane selection, resize, etc.)
set -g mouse on

# Copy 
# enter: prefix+[
# [q]uit: q (yanking will auto-quit)
#
## Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane
## start selecting text with "v"
bind-key -T copy-mode-vi 'v' send -X begin-selection
## copy text (to clipboard) with "y"
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "/usr/bin/pbcopy"
## move with vim-motions in copy mode
set-window-option -g mode-keys vi

# After prefix, hjkl repeatedly modify pane size
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# After prefix, v splits [v]ertically and v [s]plits horizontally
unbind %
bind v split-window -h

unbind '"'
unbind s
bind s split-window -v

# After prefix, S switches between [S]essions (usually 's', but now mapped to pane split)
bind S choose-session

# After prefix, r [r]enames current window (instead of `,`)
unbind ,
bind r command-prompt -I "#W" "rename-window '%%'"

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
# Fuzzy search sessions/windows/panes
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_SWITCH_CURRENT=1
# Save [prefix + C-s] sessions and Restore them [prefix + C-r] even after computer shutdown
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
